### ISSUE TITLE
QBCORE:Server:Removeitem and add item code error

### ISSUE THREAD

**Issue by Muzorm** [WaypointRP/wp-placeables#1]
Hey there, in your script you are using a remove item that has been removed a while back.
“QBCore:Server:RemoveItem” and add item code

can you fix that problem please

**Comment by BackSH00TER** [comment]
Fixed in latest commit: https://github.com/WaypointRP/wp-placeables/commit/2f1eeabf482de8c1be94d75e59c51f2c174b3c38
