### ISSUE TITLE
With v1.1.0 you can

### ISSUE THREAD

**Issue by Sina30** [WaypointRP/wp-placeables#12]
With v1.1.0 you can no longer put things on the floor. With v1.0.4 everything works great again, but no longer with the printer

**Comment by BackSH00TER** [comment]
@Sina30  is this the same error you get from wp-printers or a different issue?
https://github.com/WaypointRP/wp-printer/issues/2

Are you seeing that you can't set any items down or just the printers?

**Comment by Sina30** [comment]
We found the error, it's because the progress bar that is in the framework.lua has the old one in it and now everything is working again

But we still can't get the printer item into the inventory

**Comment by BackSH00TER** [comment]
Closing as error was figured out. Please use the issue you created in wp-printer for remaining issue there
