### ISSUE TITLE
Car vs Shopping Cart

### ISSUE THREAD

**Issue by BrainDamageTV** [WaypointRP/wp-placeables#14]
Hello, do you have a solution to the problem? Otherwise the script is great! 

[https://medal.tv/de/games/gta-v/clips/1VLKivnj2EMIWP/4kJkKnFOiXmw?invite=cr-MSxKQXQsNTM0NjMyMzAs?mobilebypass=true](url)

**Comment by BackSH00TER** [comment]
@BrainDamageTV  you can remove collisions while it is being pushed. This isn't something that I intend to change at this time tho, there are still good use cases for having the collisions enabled
