### ISSUE TITLE
Items

### ISSUE THREAD

**Issue by MacDevelopment** [WaypointRP/wp-placeables#15]
I've yet to install, but just briefly looking, why is your copy and paste items not formulated how qb-core/items.lua is?

**Comment by BackSH00TER** [comment]
@MacRP Not sure what difference you are seeing? But it is structured just fine to copy/paste in. 

If its about the key being in square brackets, ex`roadworkbarrier   = ` vs `["roadworkbarrier"] = ` , thats purely a difference in sytax
