### ISSUE TITLE
OX port

### ISSUE THREAD

**Issue by newbialywhodis** [WaypointRP/wp-placeables#2]
Could you maybe look into ox_lib/ ox_inventory implementation? It would be giga poggers

**Comment by BackSH00TER** [comment]
@newbialywhodis I've just added a framework abstraction in v1.0.1. Currently I have QB and ESX in here, but it can easily be added to. I do not run OX tho so I'm not sure of the correct implementation, nor have the means to test it. 

If you'd like to add the implementation please submit a PR

**Comment by BackSH00TER** [comment]
@newbialywhodis This is now supported in v1.0.5
